### PR TITLE
add function to replace /firmware/image/* with the actual node

### PR DESCRIPTION
**Pull request by arizaini**
* TODO:
  make the function more dynamic

Signed-off-by: arizaini <famegalaxy614@gmail.com>

### CODE REVIEW

**Comment by arizaini** [comment]
i'm not too good about writing script, but this changes is working i have tested it with untouched stock rom redmi 3s and there's no such problem

**Comment by arizaini** [comment]
my bad... haha sorry

**Comment by yshalsager** [comment]
@arizaini Thanks for this!
I'm going to merge

**Comment by arizaini** [comment]
u'r welcome mate..., for future this function need to improve like checking how much /firmware/image/* line and match it between firmware file and block partition... etc, i just adding two condition for sec.dat and splash according from your thread on xda, actually i need to check all updater-script from all device you support but i'm not have much bandwidth to download all the file

**Comment by yshalsager** [comment]
@arizaini you can use Google Cloud Shell, it can provide you with 4gb storage

**Pull request merged**
